### PR TITLE
Credit Card Number validation on length

### PR DESCRIPTION
**Pull request by ghost**
Each card type has its own range of valid numbers.
For example, the default (Visa, MasterCard, etc.) is 16.
But Amex is 15, and Maestro has card numbers between 12 and 19 digits long.

### CODE REVIEW

**Comment by vitkuzmenko** [comment]
Thank you for your PR.

Please, provide tests cases for it.

**Comment by ghost** [comment]
Will do, thanks

**Comment by ghost** [comment]
Here are the test cases I used to check the length validation: https://stripe.com/docs/testing
About Visa cards with only 13 digits (like this `4222 2222 2222 2` presented on this page: https://www.paypalobjects.com/en_GB/vhelp/paypalmanager_help/credit_card_numbers.htm), it's a bit dubious, because PayPal uses their daughter company Braintree for CC validation, and in the Braintree SDK, Visa are allowed only with 16 digits. 
I wonder if this page is still relevant.

**Comment by vitkuzmenko** [comment]
I mean Unit tests in `CreditCardValidatorTests.swift` file.

**Comment by ghost** [comment]
Yes, of course.
It's just that the case of Visa card with 13 characters is in contradiction compared to the previous test cases.
What do you think? Should we allow Visa cards for 13 and 16 characters? Only 16?

**Comment by vitkuzmenko** [comment]
I think we should accept this requirements: https://en.wikipedia.org/wiki/Payment_card_number

**Comment by ghost** [comment]
Great, thanks!
I will adjust the PR accordingly.

**Comment by ghost** [comment]
@vitkuzmenko Updated the source class and added tests.
I couldn't find a valid Mastercard number with less than 16 char though.

**Comment by vitkuzmenko** [comment]
Thanks! I review it in few days.

**Pull request merged**
